let bhavas  = [{
    bNo : 1,
    SL  : "Ju",
    DAL : "Su",
    BHL : "Ra",
    ANL : "Ra",
    DEG : 269.38,
    PL  : "",
    PSL : "",
    NL  : "",
    PSU : "",
    SSL : ""},
    {
        bNo : 1,
        SL  : "",
        DAL : "",
        BHL : "",
        ANL : "",
        DEG : 273.85,
        PL  : "Ke",
        PSL : "Sa",
        NL  : "Su",
        PSU : "Sa",
        SSL : "Ve"},
                     {
        bNo : 2,
        SL  : "Sa",
        DAL : "Ma",
        BHL : "Me",
        ANL : "Sa",
        DEG : 301.77,
        PL  : "", PSL : "", NL  : "",PSU : "",SSL : ""},
        {
            bNo : 3,
            SL  : "Ju",
            DAL : "Sa",
            BHL : "Me",
            ANL : "Ke",
            DEG : 335.82,
            PL  : "",
            PSL : "",
            NL  : "",
            PSU : "",
            SSL : ""},
            {
                bNo : 3,
                SL  : "",
                DAL : "",
                BHL : "",
                ANL : "",
                DEG : 8.04,
                PL  : "Mo",
                PSL : "Ma",
                NL  : "Ke",
                PSU : "Ju",
                SSL : "Sa"},
            {
                bNo : 4,
                SL  : "Ma",
                DAL : "Ke",
                BHL : "Ju",
                ANL : "Sa",
                DEG : 8.05,
                PL  : "", PSL : "",NL  : "",PSU : "",SSL : ""},
                {
                    bNo : 5,
                    SL  : "Ve",
                    DAL : "Su",
                    BHL : "Me",
                    ANL : "Ju",
                    DEG : 36.61,
                    PL  : "", PSL : "",NL  : "",PSU : "",SSL : ""},
                    {
                        bNo : 6,
                        SL  : "Me",
                        DAL : "Ma",
                        BHL : "Ve",
                        ANL : "Ve",
                        DEG : 62.79,
                        PL  : "", PSL : "",NL  : "",PSU : "",SSL : ""},
                        {
                            bNo : 7,
                            SL  : "Me",
                            DAL : "Ju",
                            BHL : "Su",
                            ANL : "Ve",
                            DEG : 89.38,
                            PL  : "",
                             PSL : "",
                             NL  : "",
                             PSU : "",
                             SSL : ""},
                             {
                                bNo : 7,
                                SL  : "",
                                DAL : "",
                                BHL : "",
                                ANL : "",
                                DEG : 93.85,
                                PL  : "Ra",
                                 PSL : "Mo",
                                 NL  : "Sa",
                                 PSU : "Sa",
                                 SSL : "Me"},
                             {
                                bNo : 8,
                                SL  : "Su",
                                DAL : "Ke",
                                BHL : "Ve",
                                ANL : "Ra",
                                DEG : 121.77,
                                PL  : "",
                                 PSL : "",
                                 NL  : "",
                                 PSU : "",
                                 SSL : ""},
                                 {
                                    bNo : 8,
                                    SL  : "",
                                    DAL : "",
                                    BHL : "",
                                    ANL : "",
                                    DEG : 122.50,
                                    PL  : "Ma",
                                     PSL : "Su",
                                     NL  : "Ke",
                                     PSU : "Ve",
                                     SSL : "Sa"},
                                 {
                                    bNo : 9,
                                    SL  : "Me",
                                    DAL : "Su",
                                    BHL : "Me",
                                    ANL : "Su",
                                    DEG : 155.82,
                                    PL  : "",
                                     PSL : "",
                                     NL  : "",
                                     PSU : "",
                                     SSL : ""},
                                     {
                                        bNo : 9,
                                        SL  : "",
                                        DAL : "",
                                        BHL : "",
                                        ANL : "",
                                        DEG : 170.33,
                                        PL  : "Sa",
                                         PSL : "Me",
                                         NL  : "Mo",
                                         PSU : "Ke",
                                         SSL : "Sa"},
                                         {
                                            bNo : 9,
                                            SL  : "",
                                            DAL : "",
                                            BHL : "",
                                            ANL : "",
                                            DEG : 177.27,
                                            PL  : "Ju",
                                             PSL : "Me",
                                             NL  : "Ma",
                                             PSU : "Ju",
                                             SSL : "Ve"},
                                             {
                                                bNo : 9,
                                                SL  : "",
                                                DAL : "",
                                                BHL : "",
                                                ANL : "",
                                                DEG : 177.35,
                                                PL  : "Su",
                                                 PSL : "Me",
                                                 NL  : "Ma",
                                                 PSU : "Ju",
                                                 SSL : "Su"},
                                                 {
                                                    bNo : 9,
                                                    SL  : "",
                                                    DAL : "",
                                                    BHL : "",
                                                    ANL : "",
                                                    DEG : 186.29,
                                                    PL  : "Me",
                                                     PSL : "Ve",
                                                     NL  : "Ma",
                                                     PSU : "Mo",
                                                     SSL : "Me"},
                                     {
                                        bNo : 10,
                                        SL  : "Ve",
                                        DAL : "Ra",
                                        BHL : "Ra",
                                        ANL : "Ve",
                                        DEG : 188.05,
                                        PL  : "",
                                         PSL : "",NL  : "",PSU : "",SSL : ""},
                                         {
                                            bNo : 11,
                                            SL  : "Ma",
                                            DAL : "Sa",
                                            BHL : "Me",
                                            ANL : "Ra",
                                            DEG : 216.61,
                                            PL  : "",
                                             PSL : "",
                                             NL  : "",
                                             PSU : "",
                                             SSL : ""},
                                             {
                                                bNo : 11,
                                                SL  : "",
                                                DAL : "",
                                                BHL : "",
                                                ANL : "",
                                                DEG : 222.45,
                                                PL  : "Ve",
                                                 PSL : "Ma",
                                                 NL  : "Sa",
                                                 PSU : "Ma",
                                                 SSL : "Sa"},
                                             {
                                                bNo : 12,
                                                SL  : "Ju",
                                                DAL : "Ke",
                                                BHL : "Ve",
                                                ANL : "Me",
                                                DEG : 242.79,
                                                PL  : "", PSL : "",NL  : "",PSU : "",SSL : ""}
                
];
export default bhavas;

